# Generated by Django 3.2.7 on 2021-09-30 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empno', models.IntegerField(db_column='EMPNO')),
                ('ename', models.CharField(blank=True, db_column='ENAME', max_length=20, null=True)),
                ('job', models.CharField(blank=True, db_column='JOB', max_length=9, null=True)),
                ('mgr', models.IntegerField(blank=True, db_column='MGR', null=True)),
                ('hiredate', models.DateField(blank=True, db_column='HIREDATE', null=True)),
                ('sal', models.IntegerField(blank=True, db_column='SAL', null=True)),
                ('comm', models.IntegerField(blank=True, db_column='COMM', null=True)),
                ('deptno', models.IntegerField(blank=True, db_column='DEPTNO', null=True)),
            ],
        ),
    ]
